import { ProviderReplayCursor } from "@betterc0de/schema/provider-replay"
import { buildRemoteWsUrl, getBackendMode, getRemoteToken } from "./runtime"
import type { WsEventHandler } from "./types"

const pendingRpc = new Map<
  string,
  {
    socket: WebSocket
    timer: ReturnType<typeof setTimeout>
    resolve: (value: unknown) => void
    reject: (error: Error) => void
  }
>()
let rpcIdCounter = 0

// Process-lifetime cursor shared by reconnecting sockets. The journal id is
// generated by the backend, so a backend restart safely resets the sequence
// instead of causing a high cursor from the previous process to hide events.
const providerReplayCursor = new ProviderReplayCursor()
let activeSocket: WebSocket | null = null
let cancelActiveConnection: (() => void) | null = null

export function connectWs(
  port: number = 3773,
  token?: string,
  onEvent?: WsEventHandler,
  onOpenRef?: { current: (() => void) | null },
  onClose?: () => void,
  signal?: AbortSignal
): Promise<WebSocket> {
  if (signal?.aborted)
    return Promise.reject(new Error("WebSocket connection cancelled"))
  const url =
    getBackendMode() === "remote_http"
      ? buildRemoteWsUrl()
      : `ws://127.0.0.1:${port}/ws`

  const isRemote = getBackendMode() === "remote_http"
  const effectiveToken = isRemote ? token || getRemoteToken() : ""

  return new Promise((resolve, reject) => {
    cancelActiveConnection?.()
    const ws = new WebSocket(url)
    let settled = false
    let authed = false
    activeSocket = ws
    let closed = false

    const finish = (error: Error, notify = true) => {
      if (closed) return
      closed = true
      clearTimeout(authTimer)
      signal?.removeEventListener("abort", abort)
      for (const [id, pending] of pendingRpc) {
        if (pending.socket !== ws) continue
        pendingRpc.delete(id)
        clearTimeout(pending.timer)
        pending.reject(error)
      }
      if (!settled) {
        settled = true
        reject(error)
      }
      if (activeSocket === ws) {
        activeSocket = null
        cancelActiveConnection = null
        if (notify) onClose?.()
      }
    }
    const cancel = (error: Error, notify = true) => {
      if (closed) return
      finish(error, notify)
      ws.close()
    }
    const abort = () => cancel(new Error("WebSocket connection cancelled"))
    // A connected socket without auth_ok must not leave the renderer waiting
    // forever. Its owner retries using the backend's current port.
    const authTimer = setTimeout(
      () => cancel(new Error("WebSocket authentication timed out")),
      10_000
    )
    cancelActiveConnection = () =>
      cancel(new Error("WebSocket connection superseded"), false)
    signal?.addEventListener("abort", abort, { once: true })

    ws.onopen = () => {
      if (closed || activeSocket !== ws) return
      // Local Electron connections are authenticated during the upgrade by
      // the main-process interceptor. Same-origin remote browsers authenticate
      // with an HttpOnly cookie during upgrade; an explicit bearer remains as
      // a compatibility path for manually configured remote backends.
      if (!isRemote || !effectiveToken) return
      try {
        ws.send(JSON.stringify({ type: "auth", token: effectiveToken }))
      } catch (error) {
        cancel(error instanceof Error ? error : new Error(String(error)))
      }
    }

    ws.onerror = () => {
      cancel(new Error(`WebSocket failed to connect to ${url}`))
    }

    ws.onmessage = (event) => {
      if (closed || activeSocket !== ws) return
      try {
        const data = JSON.parse(event.data)
        if (!authed) {
          if (data?.type === "auth_ok") {
            authed = true
            clearTimeout(authTimer)
            const replay = providerReplayCursor.negotiate(data.replay)
            if (replay) ws.send(JSON.stringify(replay))
            if (!settled) {
              settled = true
              resolve(ws)
              onOpenRef?.current?.()
            }
          }
          return
        }

        if (data.id && pendingRpc.get(data.id)?.socket === ws) {
          const pending = pendingRpc.get(data.id)!
          pendingRpc.delete(data.id)
          clearTimeout(pending.timer)
          if (data.error) {
            pending.reject(new Error(data.error.message || "RPC error"))
          } else {
            pending.resolve(data.result)
          }
          return
        }

        if (onEvent) {
          providerReplayCursor.deliver(data, (frame) => {
            if (frame.type === "provider_replay_gap") {
              onEvent({ channel: "provider.replayGap", data: frame })
            } else if (typeof frame.channel === "string") {
              onEvent({ ...frame, channel: frame.channel, data: frame.data })
            }
          })
        }
      } catch {
        // ignore parse errors
      }
    }

    ws.onclose = (event) => {
      finish(
        new Error(
          event.code === 4401
            ? "WebSocket auth rejected"
            : authed
              ? `WebSocket closed during RPC (code ${event.code})`
              : `WebSocket closed before auth (code ${event.code})`
        )
      )
    }
  })
}

export function wsRpc(
  ws: WebSocket,
  method: string,
  params?: Record<string, unknown>
): Promise<unknown> {
  const id = String(++rpcIdCounter)
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      if (pendingRpc.has(id)) {
        pendingRpc.delete(id)
        reject(new Error(`RPC timeout: ${method}`))
      }
    }, 30000)
    pendingRpc.set(id, { socket: ws, timer, resolve, reject })
    try {
      ws.send(JSON.stringify({ method, id, params: params ?? {} }))
    } catch (error) {
      pendingRpc.delete(id)
      clearTimeout(timer)
      reject(error instanceof Error ? error : new Error(String(error)))
    }
  })
}
