import type {
  ProviderSendTurnInput as SchemaProviderSendTurnInput,
} from "@betterc0de/schema"

export type ProviderSendTurnInput = SchemaProviderSendTurnInput & {
  readonly dispatchTurnId?: string
}

export {
  approvalRequestId,
  applyClaudePromptEffortPrefix,
  buildProviderOptionSelectionsFromDescriptors,
  getProviderOptionCurrentValue,
  getProviderOptionDescriptors,
  eventId,
  getModelSelectionBooleanOptionValue,
  getModelSelectionStringOptionValue,
  parseTurnDiffFilesFromUnifiedDiff,
  normalizeModelSlug,
  resolvePromptInjectedEffort,
  resolveSelectableModel,
  historyMessageSchema,
  modelSelectionSchema,
  providerApprovalDecisionSchema,
  permissionUpdateSchema,
  sdkPermissionModeSchema,
  providerCapabilitiesSchema,
  providerKindSchema,
  providerRefsSchema,
  providerRuntimeEventSchema,
  runtimeEventRawSchema,
  runtimeEventRawSourceSchema,
  providerSendTurnInputSchema,
  providerSessionSchema,
  requestKindSchema,
  runtimeErrorClassSchema,
  runtimeItemId,
  streamKindSchema,
  threadId,
  toolDeniedPayloadSchema,
  turnId,
  type ApprovalRequestId,
  type EventId,
  type HistoryMessage,
  type ModelCapabilities,
  type ModelSelection,
  type ProviderAdapterShape,
  type ProviderApprovalDecision,
  type ProviderAgent,
  type ProviderCapabilities,
  type ProviderCatalogEntry,
  type ProviderInstanceMetadata,
  type ProviderOptionDescriptor,
  type ProviderKind,
  type ProviderModel,
  type ProviderRefs,
  type PermissionUpdate,
  type SdkPermissionModeValue,
  type ProviderSkill,
  type ProviderSlashCommand,
  type ProviderRuntimeEvent,
  type ProviderSession,
  type ProviderThreadSnapshot,
  type ProviderTool,
  type RequestKind,
  type RuntimeEventRaw,
  type RuntimeEventRawSource,
  type RuntimeErrorClass,
  type RuntimeItemId,
  type StreamKind,
  type ThreadId,
  type ToolDeniedPayload,
  type TurnDiffFileSummary,
  type TurnId,
} from "@betterc0de/schema"
