export interface BetterC0deKeybindDefault {
  id: string
  command: string
  binding: string
  description: string
  slash?: string
  handling?: string
}

export const BETTERC0DE_KEYBIND_DEFAULTS: BetterC0deKeybindDefault[] = [
  {
    id: "leader",
    command: "leader",
    binding: "ctrl+x",
    description: "Leader key for keybind combinations",
  },
  {
    id: "app_exit",
    command: "app.exit",
    binding: "ctrl+c, ctrl+d, <leader>q",
    description: "Exit the application",
  },
  {
    id: "app_debug",
    command: "app.debug",
    binding: "none",
    description: "Toggle debug console",
    slash: "/console",
  },
  {
    id: "app_console",
    command: "app.console",
    binding: "none",
    description: "Toggle application console",
    slash: "/console",
  },
  {
    id: "app_heap_snapshot",
    command: "app.heap_snapshot",
    binding: "none",
    description: "Write backend heap snapshot",
    slash: "/heap-snapshot",
  },
  {
    id: "app_toggle_animations",
    command: "app.toggle.animations",
    binding: "none",
    description: "Toggle animations",
    slash: "/animations",
  },
  {
    id: "app_toggle_file_context",
    command: "app.toggle.file_context",
    binding: "none",
    description: "Toggle file context",
    slash: "/file-context",
  },
  {
    id: "app_toggle_diffwrap",
    command: "app.toggle.diffwrap",
    binding: "none",
    description: "Toggle diff wrapping",
    slash: "/diffwrap",
  },
  {
    id: "app_toggle_paste_summary",
    command: "app.toggle.paste_summary",
    binding: "none",
    description: "Show paste behavior (legacy command)",
    slash: "/paste-summary",
  },
  {
    id: "app_toggle_session_directory_filter",
    command: "app.toggle.session_directory_filter",
    binding: "none",
    description: "Toggle session directory filtering",
    slash: "/session-directory-filter",
  },
  {
    id: "command_list",
    command: "command.palette.show",
    binding: "ctrl+p",
    description: "List available commands",
    slash: "/command-palette",
  },
  {
    id: "help_show",
    command: "help.show",
    binding: "none",
    description: "Open help dialog",
    slash: "/help",
  },
  {
    id: "docs_open",
    command: "docs.open",
    binding: "none",
    description: "Open documentation",
    slash: "/docs",
  },
  {
    id: "editor_open",
    command: "prompt.editor",
    binding: "<leader>e",
    description: "Open external editor",
    slash: "/open",
  },
  {
    id: "theme_list",
    command: "theme.switch",
    binding: "<leader>t",
    description: "List available themes",
    slash: "/themes",
  },
  {
    id: "theme_switch_mode",
    command: "theme.switch_mode",
    binding: "none",
    description: "Switch between light and dark theme mode",
    slash: "/theme-mode",
  },
  {
    id: "theme_mode_lock",
    command: "theme.mode.lock",
    binding: "none",
    description: "Lock or unlock theme mode",
    slash: "/theme-mode-lock",
  },
  {
    id: "sidebar_toggle",
    command: "session.sidebar.toggle",
    binding: "<leader>b",
    description: "Toggle sidebar",
    slash: "/sidebar",
  },
  {
    id: "scrollbar_toggle",
    command: "session.toggle.scrollbar",
    binding: "none",
    description: "Toggle session scrollbar",
    slash: "/scrollbar",
  },
  {
    id: "status_view",
    command: "betterc0de.status",
    binding: "<leader>s",
    description: "View status",
    slash: "/status",
  },
  {
    id: "session_export",
    command: "session.export",
    binding: "<leader>x",
    description: "Export session transcript",
    slash: "/export",
  },
  {
    id: "session_copy",
    command: "session.copy",
    binding: "none",
    description: "Copy session transcript",
    slash: "/copy",
  },
  {
    id: "session_new",
    command: "session.new",
    binding: "<leader>n",
    description: "Create a new session",
    slash: "/new",
  },
  {
    id: "session_list",
    command: "session.list",
    binding: "<leader>l",
    description: "List all sessions",
    slash: "/sessions",
  },
  {
    id: "session_timeline",
    command: "session.timeline",
    binding: "<leader>g",
    description: "Show session timeline",
    slash: "/timeline",
  },
  {
    id: "session_fork",
    command: "session.fork",
    binding: "none",
    description: "Fork session from message",
    slash: "/fork",
  },
  {
    id: "session_rename",
    command: "session.rename",
    binding: "ctrl+r",
    description: "Rename session",
    slash: "/rename",
  },
  {
    id: "session_delete",
    command: "session.delete",
    binding: "ctrl+d",
    description: "Delete session",
    slash: "/delete-session",
  },
  {
    id: "session_share",
    command: "session.share",
    binding: "none",
    description: "Share current session",
    slash: "/share",
  },
  {
    id: "session_unshare",
    command: "session.unshare",
    binding: "none",
    description: "Unshare current session",
    slash: "/unshare",
  },
  {
    id: "session_interrupt",
    command: "session.interrupt",
    binding: "escape",
    description: "Interrupt current session",
    slash: "/interrupt",
  },
  {
    id: "session_compact",
    command: "session.compact",
    binding: "<leader>c",
    description: "Compact the session",
    slash: "/compact",
  },
  {
    id: "session_toggle_timestamps",
    command: "session.toggle.timestamps",
    binding: "none",
    description: "Toggle message timestamps",
    slash: "/timestamps",
  },
  {
    id: "session_toggle_generic_tool_output",
    command: "session.toggle.generic_tool_output",
    binding: "none",
    description: "Toggle generic tool output",
    slash: "/generic-tool-output",
  },
  {
    id: "session_child_first",
    command: "session.child.first",
    binding: "<leader>down",
    description: "Go to first child session",
    slash: "/child",
  },
  {
    id: "session_child_cycle",
    command: "session.child.next",
    binding: "right",
    description: "Go to next child session",
    slash: "/child-next",
  },
  {
    id: "session_child_cycle_reverse",
    command: "session.child.previous",
    binding: "left",
    description: "Go to previous child session",
    slash: "/child-previous",
  },
  {
    id: "session_parent",
    command: "session.parent",
    binding: "up",
    description: "Go to parent session",
    slash: "/parent",
  },
  {
    id: "session_pin_toggle",
    command: "session.pin.toggle",
    binding: "ctrl+f",
    description: "Pin or unpin session",
    slash: "/pin",
  },
  ...Array.from({ length: 9 }, (_, index) => ({
    id: `session_quick_switch_${index + 1}`,
    command: `session.quick_switch.${index + 1}`,
    binding: `<leader>${index + 1}`,
    description: `Switch to session quick slot ${index + 1}`,
    slash: `/quick-switch ${index + 1}`,
  })),
  {
    id: "stash_delete",
    command: "stash.delete",
    binding: "ctrl+d",
    description: "Delete stash entry",
    slash: "/stash-delete",
  },
  {
    id: "model_provider_list",
    command: "model.dialog.provider",
    binding: "ctrl+a",
    description: "Open provider list from model dialog",
    slash: "/providers",
  },
  {
    id: "model_favorite_toggle",
    command: "model.dialog.favorite",
    binding: "ctrl+f",
    description: "Toggle model favorite status",
    slash: "/favorite-toggle",
  },
  {
    id: "model_list",
    command: "model.list",
    binding: "<leader>m",
    description: "List available models",
    slash: "/model",
  },
  {
    id: "model_cycle_recent",
    command: "model.cycle_recent",
    binding: "f2",
    description: "Next recently used model",
    slash: "/model-next",
  },
  {
    id: "model_cycle_recent_reverse",
    command: "model.cycle_recent_reverse",
    binding: "shift+f2",
    description: "Previous recently used model",
    slash: "/model-previous",
  },
  {
    id: "model_cycle_favorite",
    command: "model.cycle_favorite",
    binding: "none",
    description: "Next favorite model",
    slash: "/favorite-next",
  },
  {
    id: "model_cycle_favorite_reverse",
    command: "model.cycle_favorite_reverse",
    binding: "none",
    description: "Previous favorite model",
    slash: "/favorite-previous",
  },
  {
    id: "mcp_list",
    command: "mcp.list",
    binding: "none",
    description: "List MCP servers",
    slash: "/mcps",
  },
  {
    id: "provider_connect",
    command: "provider.connect",
    binding: "none",
    description: "Connect provider",
    slash: "/connect",
  },
  {
    id: "console_org_switch",
    command: "console.org.switch",
    binding: "none",
    description: "Switch console organization",
    slash: "/org",
  },
  {
    id: "agent_list",
    command: "agent.list",
    binding: "<leader>a",
    description: "List agents",
    slash: "/agents",
  },
  {
    id: "agent_cycle",
    command: "agent.cycle",
    binding: "tab",
    description: "Next agent",
    slash: "/agent",
  },
  {
    id: "agent_cycle_reverse",
    command: "agent.cycle.reverse",
    binding: "shift+tab",
    description: "Previous agent",
    slash: "/agent-previous",
  },
  {
    id: "variant_cycle",
    command: "variant.cycle",
    binding: "ctrl+t",
    description: "Cycle model variants",
    slash: "/variant.cycle",
  },
  {
    id: "variant_list",
    command: "variant.list",
    binding: "none",
    description: "List model variants",
    slash: "/variants",
  },
  {
    id: "messages_page_up",
    command: "session.page.up",
    binding: "pageup, ctrl+alt+b",
    description: "Scroll messages up by one page",
    slash: "/page-up",
  },
  {
    id: "messages_page_down",
    command: "session.page.down",
    binding: "pagedown, ctrl+alt+f",
    description: "Scroll messages down by one page",
    slash: "/page-down",
  },
  {
    id: "messages_line_up",
    command: "session.line.up",
    binding: "ctrl+alt+y",
    description: "Scroll messages up by one line",
    slash: "/line-up",
  },
  {
    id: "messages_line_down",
    command: "session.line.down",
    binding: "ctrl+alt+e",
    description: "Scroll messages down by one line",
    slash: "/line-down",
  },
  {
    id: "messages_half_page_up",
    command: "session.half.page.up",
    binding: "ctrl+alt+u",
    description: "Scroll messages up by half page",
    slash: "/half-page-up",
  },
  {
    id: "messages_half_page_down",
    command: "session.half.page.down",
    binding: "ctrl+alt+d",
    description: "Scroll messages down by half page",
    slash: "/half-page-down",
  },
  {
    id: "messages_first",
    command: "session.first",
    binding: "ctrl+g, home",
    description: "Navigate to first message",
    slash: "/first",
  },
  {
    id: "messages_last",
    command: "session.last",
    binding: "ctrl+alt+g, end",
    description: "Navigate to last message",
    slash: "/last",
  },
  {
    id: "messages_next",
    command: "session.message.next",
    binding: "none",
    description: "Navigate to next message",
    slash: "/next-message",
  },
  {
    id: "messages_previous",
    command: "session.message.previous",
    binding: "none",
    description: "Navigate to previous message",
    slash: "/previous-message",
  },
  {
    id: "messages_last_user",
    command: "session.messages_last_user",
    binding: "none",
    description: "Navigate to last user message",
    slash: "/last-user",
  },
  {
    id: "messages_copy",
    command: "messages.copy",
    binding: "<leader>y",
    description: "Copy message",
    slash: "/copy-last",
  },
  {
    id: "messages_undo",
    command: "session.undo",
    binding: "<leader>u",
    description: "Undo message and file changes",
    slash: "/undo",
  },
  {
    id: "messages_redo",
    command: "session.redo",
    binding: "<leader>r",
    description: "Redo message and file changes",
    slash: "/redo",
  },
  {
    id: "messages_toggle_conceal",
    command: "session.toggle.conceal",
    binding: "<leader>h",
    description: "Toggle code block concealment",
    slash: "/conceal",
  },
  {
    id: "tool_details",
    command: "session.toggle.actions",
    binding: "none",
    description: "Toggle tool details visibility",
    slash: "/tool-details",
  },
  {
    id: "display_thinking",
    command: "session.toggle.thinking",
    binding: "none",
    description: "Toggle thinking blocks visibility",
    slash: "/thinking",
  },
  {
    id: "prompt_editor_context_clear",
    command: "prompt.editor_context.clear",
    binding: "none",
    description: "Clear editor context",
    slash: "/editor-context-clear",
  },
  {
    id: "prompt_skills",
    command: "prompt.skills",
    binding: "none",
    description: "Open skill selector",
    slash: "/skills",
  },
  {
    id: "prompt_stash",
    command: "prompt.stash",
    binding: "none",
    description: "Stash prompt",
    slash: "/stash",
  },
  {
    id: "prompt_stash_pop",
    command: "prompt.stash.pop",
    binding: "none",
    description: "Pop stashed prompt",
    slash: "/stash-pop",
  },
  {
    id: "prompt_stash_list",
    command: "prompt.stash.list",
    binding: "none",
    description: "List stashed prompts",
    slash: "/stashes",
  },
  {
    id: "terminal_title_toggle",
    command: "terminal.title.toggle",
    binding: "none",
    description: "Toggle terminal title updates",
    slash: "/terminal-title",
  },
  {
    id: "terminal_suspend",
    command: "terminal.suspend",
    binding: "ctrl+z",
    description: "Suspend terminal",
    slash: "/terminal",
  },
  {
    id: "tips_toggle",
    command: "tips.toggle",
    binding: "<leader>h",
    description: "Toggle tips on home screen",
    slash: "/tips",
  },
  {
    id: "plugin_manager",
    command: "plugins.list",
    binding: "none",
    description: "Open plugin manager dialog",
    slash: "/plugins",
  },
  {
    id: "plugin_install",
    command: "plugins.install",
    binding: "none",
    description: "Install plugin",
    slash: "/plugin-install",
  },
  {
    id: "which_key_toggle",
    command: "which-key.toggle",
    binding: "ctrl+alt+k",
    description: "Toggle which-key panel",
    slash: "/which-key",
  },
  {
    id: "which_key_layout_toggle",
    command: "which-key.layout.toggle",
    binding: "ctrl+alt+shift+k",
    description: "Switch which-key layout",
    slash: "/which-key",
  },
  {
    id: "which_key_pending_toggle",
    command: "which-key.pending.toggle",
    binding: "ctrl+alt+shift+p",
    description: "Toggle which-key pending preview",
    slash: "/which-key",
  },
  {
    id: "which_key_group_previous",
    command: "which-key.group.previous",
    binding: "ctrl+alt+left, ctrl+alt+[",
    description: "Previous which-key group",
    slash: "/which-key",
  },
  {
    id: "which_key_group_next",
    command: "which-key.group.next",
    binding: "ctrl+alt+right, ctrl+alt+]",
    description: "Next which-key group",
    slash: "/which-key",
  },
  {
    id: "which_key_scroll_up",
    command: "which-key.scroll.up",
    binding: "ctrl+alt+up, ctrl+alt+p",
    description: "Scroll which-key up",
    slash: "/which-key",
  },
  {
    id: "which_key_scroll_down",
    command: "which-key.scroll.down",
    binding: "ctrl+alt+down, ctrl+alt+n",
    description: "Scroll which-key down",
    slash: "/which-key",
  },
  {
    id: "which_key_page_up",
    command: "which-key.page.up",
    binding: "ctrl+alt+pageup",
    description: "Page which-key up",
    slash: "/which-key",
  },
  {
    id: "which_key_page_down",
    command: "which-key.page.down",
    binding: "ctrl+alt+pagedown",
    description: "Page which-key down",
    slash: "/which-key",
  },
  {
    id: "which_key_home",
    command: "which-key.home",
    binding: "ctrl+alt+home",
    description: "Jump to first which-key binding",
    slash: "/which-key",
  },
  {
    id: "which_key_end",
    command: "which-key.end",
    binding: "ctrl+alt+end",
    description: "Jump to last which-key binding",
    slash: "/which-key",
  },
  {
    id: "workspace_set",
    command: "workspace.set",
    binding: "none",
    description: "Set workspace",
    slash: "/warp",
  },
  {
    id: "dialog.select.prev",
    command: "dialog.select.prev",
    binding: "up, ctrl+p",
    description: "Move to previous dialog item",
  },
  {
    id: "dialog.select.next",
    command: "dialog.select.next",
    binding: "down, ctrl+n",
    description: "Move to next dialog item",
  },
  {
    id: "dialog.select.page_up",
    command: "dialog.select.page_up",
    binding: "pageup",
    description: "Move up one page in dialog",
  },
  {
    id: "dialog.select.page_down",
    command: "dialog.select.page_down",
    binding: "pagedown",
    description: "Move down one page in dialog",
  },
  {
    id: "dialog.select.home",
    command: "dialog.select.home",
    binding: "home",
    description: "Move to first dialog item",
  },
  {
    id: "dialog.select.end",
    command: "dialog.select.end",
    binding: "end",
    description: "Move to last dialog item",
  },
  {
    id: "dialog.select.submit",
    command: "dialog.select.submit",
    binding: "return",
    description: "Submit selected dialog item",
  },
  {
    id: "dialog.prompt.submit",
    command: "dialog.prompt.submit",
    binding: "return",
    description: "Submit dialog prompt",
  },
  {
    id: "dialog.mcp.toggle",
    command: "dialog.mcp.toggle",
    binding: "space",
    description: "Toggle MCP in MCP dialog",
    slash: "/mcp-toggle",
  },
  {
    id: "prompt.autocomplete.prev",
    command: "prompt.autocomplete.prev",
    binding: "up, ctrl+p",
    description: "Move to previous autocomplete item",
  },
  {
    id: "prompt.autocomplete.next",
    command: "prompt.autocomplete.next",
    binding: "down, ctrl+n",
    description: "Move to next autocomplete item",
  },
  {
    id: "prompt.autocomplete.hide",
    command: "prompt.autocomplete.hide",
    binding: "escape",
    description: "Hide autocomplete",
  },
  {
    id: "prompt.autocomplete.select",
    command: "prompt.autocomplete.select",
    binding: "return",
    description: "Select autocomplete item",
  },
  {
    id: "prompt.autocomplete.complete",
    command: "prompt.autocomplete.complete",
    binding: "tab",
    description: "Complete autocomplete item",
  },
  {
    id: "permission.prompt.fullscreen",
    command: "permission.prompt.fullscreen",
    binding: "ctrl+f",
    description: "Toggle permission prompt fullscreen",
    slash: "/permission-fullscreen",
  },
  {
    id: "plugins.toggle",
    command: "plugins.toggle",
    binding: "space",
    description: "Toggle plugin",
    slash: "/plugins",
  },
  {
    id: "dialog.plugins.install",
    command: "dialog.plugins.install",
    binding: "shift+i",
    description: "Install plugin from plugin dialog",
    slash: "/plugin-install",
  },
]

export const BETTERC0DE_COMPOSER_KEYBIND_DEFAULTS: BetterC0deKeybindDefault[] = [
  {
    id: "prompt_submit",
    command: "prompt.submit",
    binding: "none",
    description: "Submit prompt",
    handling: "Submit button / input.submit",
  },
  {
    id: "input_clear",
    command: "prompt.clear",
    binding: "ctrl+c",
    description: "Clear input field when no text is selected",
    handling: "Composer",
  },
  {
    id: "input_paste",
    command: "prompt.paste",
    binding: "ctrl+v",
    description: "Paste from clipboard",
    handling: "Native textarea",
  },
  {
    id: "input_submit",
    command: "input.submit",
    binding: "return",
    description: "Submit input",
    handling: "Composer submit",
  },
  {
    id: "input_newline",
    command: "input.newline",
    binding: "shift+return, ctrl+return, alt+return, ctrl+j",
    description: "Insert newline in input",
    handling: "Composer",
  },
  {
    id: "input_move_left",
    command: "input.move.left",
    binding: "left, ctrl+b",
    description: "Move cursor left in input",
    handling: "Native textarea",
  },
  {
    id: "input_move_right",
    command: "input.move.right",
    binding: "right, ctrl+f",
    description: "Move cursor right in input",
    handling: "Native textarea",
  },
  {
    id: "input_move_up",
    command: "input.move.up",
    binding: "up",
    description: "Move cursor up in input",
    handling: "Native textarea / history at boundary",
  },
  {
    id: "input_move_down",
    command: "input.move.down",
    binding: "down",
    description: "Move cursor down in input",
    handling: "Native textarea / history at boundary",
  },
  {
    id: "input_select_left",
    command: "input.select.left",
    binding: "shift+left",
    description: "Select left in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_right",
    command: "input.select.right",
    binding: "shift+right",
    description: "Select right in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_up",
    command: "input.select.up",
    binding: "shift+up",
    description: "Select up in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_down",
    command: "input.select.down",
    binding: "shift+down",
    description: "Select down in input",
    handling: "Native textarea",
  },
  {
    id: "input_line_home",
    command: "input.line.home",
    binding: "ctrl+a",
    description: "Move to start of line in input",
    handling: "Native textarea",
  },
  {
    id: "input_line_end",
    command: "input.line.end",
    binding: "ctrl+e",
    description: "Move to end of line in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_line_home",
    command: "input.select.line.home",
    binding: "ctrl+shift+a",
    description: "Select to start of line in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_line_end",
    command: "input.select.line.end",
    binding: "ctrl+shift+e",
    description: "Select to end of line in input",
    handling: "Native textarea",
  },
  {
    id: "input_visual_line_home",
    command: "input.visual.line.home",
    binding: "alt+a",
    description: "Move to start of visual line in input",
    handling: "Native textarea",
  },
  {
    id: "input_visual_line_end",
    command: "input.visual.line.end",
    binding: "alt+e",
    description: "Move to end of visual line in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_visual_line_home",
    command: "input.select.visual.line.home",
    binding: "alt+shift+a",
    description: "Select to start of visual line in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_visual_line_end",
    command: "input.select.visual.line.end",
    binding: "alt+shift+e",
    description: "Select to end of visual line in input",
    handling: "Native textarea",
  },
  {
    id: "input_buffer_home",
    command: "input.buffer.home",
    binding: "home",
    description: "Move to start of buffer in input",
    handling: "Native textarea",
  },
  {
    id: "input_buffer_end",
    command: "input.buffer.end",
    binding: "end",
    description: "Move to end of buffer in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_buffer_home",
    command: "input.select.buffer.home",
    binding: "shift+home",
    description: "Select to start of buffer in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_buffer_end",
    command: "input.select.buffer.end",
    binding: "shift+end",
    description: "Select to end of buffer in input",
    handling: "Native textarea",
  },
  {
    id: "input_delete_line",
    command: "input.delete.line",
    binding: "ctrl+shift+d",
    description: "Delete line in input",
    handling: "Composer",
  },
  {
    id: "input_delete_to_line_end",
    command: "input.delete.to.line.end",
    binding: "ctrl+k",
    description: "Delete to end of line in input",
    handling: "Composer",
  },
  {
    id: "input_delete_to_line_start",
    command: "input.delete.to.line.start",
    binding: "ctrl+u",
    description: "Delete to start of line in input",
    handling: "Composer",
  },
  {
    id: "input_backspace",
    command: "input.backspace",
    binding: "backspace, shift+backspace",
    description: "Backspace in input",
    handling: "Native textarea / attachment delete",
  },
  {
    id: "input_delete",
    command: "input.delete",
    binding: "ctrl+d, delete, shift+delete",
    description: "Delete character in input",
    handling: "Composer/native textarea",
  },
  {
    id: "input_undo",
    command: "input.undo",
    binding: "ctrl+-, super+z",
    description: "Undo in input",
    handling: "Native textarea",
  },
  {
    id: "input_redo",
    command: "input.redo",
    binding: "ctrl+., super+shift+z",
    description: "Redo in input",
    handling: "Native textarea",
  },
  {
    id: "input_word_forward",
    command: "input.word.forward",
    binding: "alt+f, alt+right, ctrl+right",
    description: "Move word forward in input",
    handling: "Native textarea",
  },
  {
    id: "input_word_backward",
    command: "input.word.backward",
    binding: "alt+b, alt+left, ctrl+left",
    description: "Move word backward in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_word_forward",
    command: "input.select.word.forward",
    binding: "alt+shift+f, alt+shift+right",
    description: "Select word forward in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_word_backward",
    command: "input.select.word.backward",
    binding: "alt+shift+b, alt+shift+left",
    description: "Select word backward in input",
    handling: "Native textarea",
  },
  {
    id: "input_delete_word_forward",
    command: "input.delete.word.forward",
    binding: "alt+d, alt+delete, ctrl+delete",
    description: "Delete word forward in input",
    handling: "Native textarea",
  },
  {
    id: "input_delete_word_backward",
    command: "input.delete.word.backward",
    binding: "ctrl+w, ctrl+backspace, alt+backspace",
    description: "Delete word backward in input",
    handling: "Native textarea",
  },
  {
    id: "input_select_all",
    command: "input.select.all",
    binding: "super+a",
    description: "Select all in input",
    handling: "Native textarea",
  },
  {
    id: "history_previous",
    command: "prompt.history.previous",
    binding: "up",
    description: "Previous history item",
    handling: "Composer history",
  },
  {
    id: "history_next",
    command: "prompt.history.next",
    binding: "down",
    description: "Next history item",
    handling: "Composer history",
  },
]

export const BETTERC0DE_INPUT_ACTION_COMMANDS =
  BETTERC0DE_COMPOSER_KEYBIND_DEFAULTS.filter((item) =>
    item.command.startsWith("input.")
  ).map((item) => item.command)

export function findBetterC0deKeybindDefault(
  command: string
): BetterC0deKeybindDefault | undefined {
  return [...BETTERC0DE_KEYBIND_DEFAULTS, ...BETTERC0DE_COMPOSER_KEYBIND_DEFAULTS].find(
    (item) => item.command === command || item.id === command
  )
}
