/**
 * HTTP body validation schemas.
 *
 * The authoritative source of these schemas is the workspace package
 * `@betterc0de/schema` (`packages/schema/src/`), shared between the
 * backend and the renderer so request/response shapes stay synchronized
 * across process boundaries.
 *
 * This file is kept as a thin re-export so existing imports inside the
 * backend (`from "../validation"`) continue to resolve without a sweep
 * through every route file. New code should import from
 * `@betterc0de/schema` directly.
 */
export {
  chatSendSchema,
  chatInterruptSchema,
  chatRotateSessionSchema,
  chatAutoCompactionDecisionSchema,
  chatTitleSchema,
  chatQuestionsSchema,
  chatGenerateCommitMessageSchema,
  chatGeneratePrContentSchema,
  chatGenerateBranchNameSchema,
  chatGenerateThreadContextSummarySchema,
  chatGenerateSkillContentSchema,
  chatApprovalSchema,
  chatPlanApprovalSchema,
  chatPermissionModeSchema,
  chatUserInputSchema,
  chatUserInputRejectSchema,
  permissionRulesListSchema,
  permissionRuleDeleteSchema,
  type ChatPlanApprovalBody,
  type ChatPermissionModeBody,
  type PermissionRulesListBody,
  type PermissionRuleDeleteBody,
  type ChatSendBody,
  type ChatInterruptBody,
  type ChatRotateSessionBody,
  type ChatAutoCompactionDecisionBody,
  type ChatTitleBody,
  type ChatQuestionsBody,
  type ChatGenerateCommitMessageBody,
  type ChatGeneratePrContentBody,
  type ChatGenerateBranchNameBody,
  type ChatGenerateThreadContextSummaryBody,
  type ChatGenerateSkillContentBody,
  type ChatApprovalBody,
  type ChatUserInputBody,
  type ChatUserInputRejectBody,
  shellRunSchema,
  shellCapabilityRequestSchema,
  shellAbortSchema,
  toolOutputArchiveIdSchema,
  terminalOpenSchema,
  terminalWriteSchema,
  terminalResizeSchema,
  terminalReadSchema,
  type ShellRunBody,
  type ShellCapabilityRequest,
  type ShellAbortBody,
  type ToolOutputArchiveId,
  type TerminalOpenBody,
  type TerminalWriteBody,
  type TerminalResizeBody,
  type TerminalReadBody,
  threadSaveMessageSchema,
  threadSaveSchema,
  threadMetaSchema,
  threadMessageSchema,
  threadModelSwitchActivitySchema,
  threadTruncateSchema,
  threadCheckpointRevertSchema,
  threadCheckpointRecoveryResolveSchema,
  threadWorktreeCreateSchema,
  threadWorktreeRemoveSchema,
  threadWorktreeResetSchema,
  type ThreadSaveBody,
  type ThreadSaveMessage,
  type ThreadMetaBody,
  type ThreadMessageBody,
  type ThreadModelSwitchActivityBody,
  type ThreadTruncateBody,
  type ThreadCheckpointRevertBody,
  type ThreadCheckpointRecoveryResolveBody,
  type ThreadWorktreeCreateBody,
  type ThreadWorktreeRemoveBody,
  type ThreadWorktreeResetBody,
  gitCwdSchema,
  gitProfileSchema,
  type GitProfileBody,
  gitCommitSchema,
  gitDiscardSchema,
  gitOpenEditorSchema,
  gitLogSchema,
  gitCheckoutSchema,
  gitStashSchema,
  gitBranchRenameSchema,
  gitWorktreeCreateSchema,
  gitWorktreeRemoveSchema,
  gitPathsSchema,
  gitHunkActionSchema,
  type GitHunkActionInput,
  gitPushSchema,
  gitRemoteAddSchema,
  gitCheckpointSchema,
  gitCheckpointDiffSchema,
  gitCheckpointDeleteSchema,
  providerRollbackConversationSchema,
  type ProviderRollbackConversationInput,
  settingsPatchSchema,
  type SettingsPatchBody,
  workspaceSearchSchema,
  workspaceContentSearchSchema,
  workspaceQuickOpenSchema,
  workspaceMapSchema,
  workspaceProjectCommandsSchema,
  workspaceProjectAgentsSchema,
  workspaceProjectSkillsSchema,
  workspaceProjectMcpServersSchema,
  workspaceProjectInstructionsSchema,
  workspaceProjectReferencesSchema,
  workspaceProjectFormattersSchema,
  workspaceProjectFormatSchema,
  workspaceProjectLspServersSchema,
  workspaceProjectPermissionsSchema,
  workspaceProjectConfigSchema,
  workspaceProjectProvidersSchema,
  workspaceProjectPluginsSchema,
  workspaceProjectToolsSchema,
  workspaceReadSchema,
  workspaceWriteSchema,
  workspaceMkdirSchema,
  workspaceAdoptScratchSchema,
  workspaceMoveSchema,
  workspaceDeleteSchema,
  type WorkspaceSearchBody,
  type WorkspaceContentSearchBody,
  type WorkspaceQuickOpenBody,
  type WorkspaceMapBody,
  type WorkspaceProjectCommandsBody,
  type WorkspaceProjectAgentsBody,
  type WorkspaceProjectSkillsBody,
  type WorkspaceProjectMcpServersBody,
  type WorkspaceProjectInstructionsBody,
  type WorkspaceProjectReferencesBody,
  type WorkspaceProjectFormattersBody,
  type WorkspaceProjectFormatBody,
  type WorkspaceProjectLspServersBody,
  type WorkspaceProjectPermissionsBody,
  type WorkspaceProjectConfigBody,
  type WorkspaceProjectProvidersBody,
  type WorkspaceProjectPluginsBody,
  type WorkspaceProjectToolsBody,
  type WorkspaceReadBody,
  type WorkspaceWriteBody,
  type WorkspaceMkdirBody,
  type WorkspaceMoveBody,
  type WorkspaceDeleteBody,
  filesystemListSchema,
  filesystemSearchSchema,
  type FilesystemListBody,
  type FilesystemSearchBody,
} from "@betterc0de/schema"
